#!/bin/sh

# Copyright © 2012-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

for file in "$@"
do
    printf '%s: %s ... ' "$file" "$(du -sh "$file" | cut -f 1)"
    sqlite3 "$file" vacuum
    printf '%s\n' "$(du -sh "$file" | cut -f1)"
done

# vim:ts=4 sts=4 sw=4 et
