#!/bin/sh

# Copyright © 2012-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

for file in "$@"
do
    du=$(du -sh -- "$file")
    printf '%s: %s ... ' "$file" "${du%'	'*}" >&2
    sqlite3 "$file" vacuum
    du=$(du -sh -- "$file")
    printf '%s\n' "${du%'	'*}" >&2
done

# vim:ts=4 sts=4 sw=4 et
